name: cryptoexpo
description: An app that helps crypto beginners and experts alike decide when to buy/sell crypto.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  alphabet_scroll_view: ^0.3.1 # used to quickly scroll to alphabet in a list
  auto_size_text: ^3.0.0 #used for auto scaling of font size to fixed maxlines
  cloud_firestore: ^3.1.8   # FlutterFire library for firebase
  country_codes: ^2.1.1 # used for getting country phone codes
  country_icons: ^2.0.2 # has all country flags as icons
  crypto: ^3.0.1 # Cryptographic hashing
  csv: ^5.0.0
  cupertino_icons: ^1.0.2   # Adds the Cupertino Icons font to your application.
  device_preview: ^1.0.0 # used to preview app on different screen types of (phones, tabs, OS)
  firebase_auth: ^3.3.7   # FlutterFire library for firebase
  firebase_core: ^1.12.0   # FlutterFire library for firebase
  flutter_svg: ^1.0.3 # to display svg images
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1 # GetX Flutter solution for DI, Routing, State, Navigation, MVC
  get_storage: ^2.0.3 # key-value storage with memory and disk persistence
  google_fonts: ^2.1.0
  http: ^0.13.3
  lottie: ^1.2.2 # lottie for animated icons
  syncfusion_flutter_charts: ^19.4.52 # for drawing crypto charts
  timeago: ^3.2.2
  quiver: ^3.0.1+1

dev_dependencies:
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/json/
    - assets/lottie/
    - assets/images/
    - assets/images/default.png
    - assets/images/defaultDark.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
